BEGIN;
CREATE TABLE IF NOT EXISTS wz_businesses(id TEXT PRIMARY KEY,name TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO wz_businesses(id,name) VALUES('WZ001','WZ MANAGE PRO') ON CONFLICT(id) DO NOTHING;
ALTER TABLE wz_branches ADD COLUMN IF NOT EXISTS business_id TEXT REFERENCES wz_businesses(id);
ALTER TABLE wz_employees ADD COLUMN IF NOT EXISTS business_id TEXT REFERENCES wz_businesses(id);
ALTER TABLE wz_users ADD COLUMN IF NOT EXISTS business_id TEXT REFERENCES wz_businesses(id);
ALTER TABLE wz_transactions ADD COLUMN IF NOT EXISTS business_id TEXT REFERENCES wz_businesses(id);
ALTER TABLE wz_shift_reports ADD COLUMN IF NOT EXISTS business_id TEXT REFERENCES wz_businesses(id);
ALTER TABLE wz_push_subscriptions ADD COLUMN IF NOT EXISTS business_id TEXT REFERENCES wz_businesses(id);
UPDATE wz_branches SET business_id='WZ001' WHERE business_id IS NULL;
UPDATE wz_employees SET business_id='WZ001' WHERE business_id IS NULL;
UPDATE wz_users SET business_id='WZ001' WHERE business_id IS NULL;
UPDATE wz_transactions SET business_id='WZ001' WHERE business_id IS NULL;
UPDATE wz_shift_reports SET business_id='WZ001' WHERE business_id IS NULL;
UPDATE wz_push_subscriptions s SET business_id=u.business_id FROM wz_users u WHERE u.id=s.user_id AND s.business_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS wz_users_business_username_uq ON wz_users(business_id,username);
CREATE UNIQUE INDEX IF NOT EXISTS wz_users_business_employee_uq ON wz_users(business_id,employee_id) WHERE employee_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS wz_push_business_endpoint_uq ON wz_push_subscriptions(business_id,endpoint);
CREATE INDEX IF NOT EXISTS wz_users_business_idx ON wz_users(business_id);
CREATE INDEX IF NOT EXISTS wz_employees_business_idx ON wz_employees(business_id);
CREATE INDEX IF NOT EXISTS wz_transactions_business_idx ON wz_transactions(business_id);
CREATE INDEX IF NOT EXISTS wz_shift_reports_business_idx ON wz_shift_reports(business_id);
CREATE TABLE IF NOT EXISTS wz_app_states(business_id TEXT PRIMARY KEY REFERENCES wz_businesses(id) ON DELETE CASCADE,data JSONB NOT NULL DEFAULT '{}'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO wz_app_states(business_id,data,updated_at) SELECT 'WZ001',data,updated_at FROM wz_app_state WHERE id=1 ON CONFLICT(business_id) DO NOTHING;
INSERT INTO wz_app_states(business_id,data) VALUES('WZ001','{}'::jsonb) ON CONFLICT(business_id) DO NOTHING;
COMMIT;
